version: '3.4'

networks:
    default:

services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build: .
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql+mysqlconnector://username:password@database/mydatabase
    command: [
      "runserver"
      #"create_db"
    ]

  react_app:
    build: ./static
    ports:
      - 80:3000
    command: [
      "npm",
      "start"
    ]
    expose:
      - 3000

volumes:
  db-data: