version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  flask:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    command: [
      "runserver"
    ]

  react_app:
    build: ./static
    ports:
      - 3000:3000
    depends_on:
      - db
    command: [
      "npm",
      "start"
    ]
