"""empty message

Revision ID: 7e5b57c854e6
Revises: ed657e16ce20
Create Date: 2018-01-24 21:56:25.098793

"""

# revision identifiers, used by Alembic.
revision = '7e5b57c854e6'
down_revision = 'ed657e16ce20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
